create table person
(
    id               integer generated by default as identity
        constraint person_pk
            primary key,
    full_name        varchar(64) not null
        constraint person_full_name_ak
            unique,
    year_of_birthday integer     not null
        constraint person_year_ob_birthday_check
            check (year_of_birthday > 1900)
);

alter table person
    owner to postgres;

INSERT INTO project_1.person (id, full_name, year_of_birthday) VALUES (23, 'Petrov Petr', 1994);
INSERT INTO project_1.person (id, full_name, year_of_birthday) VALUES (6, 'Ivanov Ivan', 1979);
INSERT INTO project_1.person (id, full_name, year_of_birthday) VALUES (24, 'Sidorov Nikolay', 1978);
INSERT INTO project_1.person (id, full_name, year_of_birthday) VALUES (25, 'Krischenko Valentin', 1991);
INSERT INTO project_1.person (id, full_name, year_of_birthday) VALUES (26, 'Stepanova Olya', 1984);
INSERT INTO project_1.person (id, full_name, year_of_birthday) VALUES (27, 'Karpenko Alisa', 2002);
INSERT INTO project_1.person (id, full_name, year_of_birthday) VALUES (28, 'Nikolay Stepanov', 1984);