create table book
(
    id                  integer generated by default as identity
        constraint book_pk
            primary key,
    title               varchar(200)                                            not null,
    author              varchar(100) default 'uknown author'::character varying not null,
    year_of_publication integer,
    person_id           integer
        constraint book_person_fk
            references person
            on update cascade on delete set null
        constraint book_person_id_fk
            references person
            on delete set null
);

alter table book
    owner to postgres;

INSERT INTO project_1.book (id, title, author, year_of_publication, person_id) VALUES (8, 'Jane Eyre', 'Charlotte Bronte', 1847, null);
INSERT INTO project_1.book (id, title, author, year_of_publication, person_id) VALUES (9, 'Fahrenheit 451', 'Ray Bradbury', 1953, null);
INSERT INTO project_1.book (id, title, author, year_of_publication, person_id) VALUES (10, 'Crime and Punishment', ' Fyodor Dostoevsky', 1866, null);
INSERT INTO project_1.book (id, title, author, year_of_publication, person_id) VALUES (2, 'Anna Karenina', 'Lev Tolstoy', 1980, null);
INSERT INTO project_1.book (id, title, author, year_of_publication, person_id) VALUES (1, 'Pride and Prejudice ', 'Jane Austen', 1998, 24);
INSERT INTO project_1.book (id, title, author, year_of_publication, person_id) VALUES (4, 'Преступление и наказание ', 'Ф. Достоевский', 1975, 23);